version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    automerged_updates:
      - match:
          dependency_type: 'development'
          update_type: 'all'
      - match:
          dependency_type: 'production'
          update_type: 'semver:patch'
    ignored_updates:
      - match:
          dependency_name: 'cypress-testing-library'
      - match:
          dependency_name: 'react-testing-library'
